#!/usr/bin/env python
import sys

from twisted.python import usage

from supperfeed.build import Build


class Options(usage.Options):
    subCommands = [
        ("build", None, Build, Build.__doc__),
        ]

    def opt_version(self):
        print 'SupperFeed server v???'
        return usage.Options.opt_version(self)

    def postOptions(self):
        """Recommended if there are subcommands:"""
        if self.subCommand is None:
            self.synopsis = "spoon <subcommand>"
            raise usage.UsageError("** Please specify a subcommand (see \"Commands\").")


def run(argv=None):
    if argv is None:
        argv = sys.argv
    o = Build()
    try:
        o.parseOptions(argv[1:])
    except usage.UsageError, e:
        if hasattr(o, 'subOptions'):
            print str(o.subOptions)
        else:
            print str(o)
        print str(e)
        return 1

    return 0


if __name__ == '__main__': sys.exit(run())
