#!/bin/bash

set -e
unset CDPATH

# Use pip to install fabric, virtualenv, and autoenv, which we will need to do
# anything else
sudo pip install -U fabric
sudo pip install -U virtualenv
sudo pip install -U autoenv

# Pull down the rest of the gist, where the rest of the developer setup code
# lives
pushd fabfile
git pull
popd 

# Run fabric which installs everything else
fab --show debug brightmd

# Set up autoenv
cp fabfile/autoenv.env .env
for loc in /usr/local/bin /usr/local/opt/autoenv; do
    if [ -x $loc/activate.sh ]; then
        activate_path=$loc/activate.sh
    fi
done
. $activate_path && autoenv_authorize_env `pwd`/.env && autoenv_authorize_env `pwd`/Aorta/.env


echo "##################################################################"
echo "  You must add this to your .bash_profile or shell environment:"
echo
echo "  . $activate_path"
echo

cp fabfile/upgrade bin
